Practice: Github Actions

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -6,6 +6,12 @@ on:
   pull_request:
     branches: [ main ]
 
+  schedule:
+    - cron: '1 * * * *'
+
+  env:
+    STAGE: dev
+
 jobs:
   test-scripts:
     runs-on: ubuntu-latest
@@ -14,8 +20,19 @@ jobs:
       - name: Checkout Code
         uses: actions/checkout@v4
 
-      - name: List Files
-        run: ls -l
+  build:
+    runs-on: ubuntu-latest
+    steps:
+      - run: echo "Building the Application... ${{ github.repository }}"
 
-      - name: Run Greeting script
-        run: bash greet.sh || echo "Error"
+  test:
+    runs-on: ubuntu-latest
+    steps:
+      - run: echo "Running the tests..."
+
+  deploy:
+    runs-on: ubuntu-latest
+    needs: [build, test]
+    steps:
+      - run: echo "Deploying the Application..."
+      - rub: bash greet.sh || echo "Error..."
